### PR TITLE
fix(aws-sns-sqs): switch sns-sqs to use SQS_MANAGED key for queue

### LINKED ISSUE #1334: SnsToSqs: support SSE-SQS
`SnsToSqs` can't create an SSE-SQS encrypted queue using [new interface](https://constructs.dev/packages/@aws-solutions-constructs/aws-sns-sqs/v/2.85.2?lang=typescript#new-interface-as-of-v2580).

### Reproduction Steps

```
const topicToQueue = new SnsToSqs(this, 'TopicToQueue', {
    queueProps: {
        encryption: QueueEncryption.SQS_MANAGED,
    },
    encryptQueueWithCmk: false
}
```

### Error Log

`The new interface of SnsToSqs does not support managing encryption using the queueProps.encryption setting. To use a totally unencrypted queue (not recommended), create the queue separately and pass in the existingQueueObj prop`

[Sources](https://github.com/awslabs/aws-solutions-constructs/blob/v2.84.0/source/patterns/%40aws-solutions-constructs/aws-sns-sqs/lib/index.ts#L313-L317).

### Environment

  - **CDK CLI Version : N/A**
  - **CDK Framework Version : N/A**
  - **AWS Solutions Constructs Version : 2.58.0+**
  - **OS : N/A**
  - **Language : N/A**

### Other

There is a workaround to use `enableEncryptionWithCustomerManagedKey: false`, but it is deprecated.

SSE-SQS encrypted queues work with SNS subscriptions seamlessly, and is a simpler, cheaper alternative.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by biffgaut**
*Issue #, if available:*
Closes #1334

*Description of changes:*
Make the default queue encryption for this construct SQS_MANAGED rather than Amazon managed KMS key

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: source/patterns/@aws-solutions-constructs/aws-sns-sqs/lib/index.ts [hunk 1]
```diff
@@ -224,6 +225,7 @@ export class SnsToSqs extends Construct {
       maxReceiveCount: props.maxReceiveCount,
       enableEncryptionWithCustomerManagedKey: activeKeys.encryptQueueWithCmk,
       encryptionKey: activeKeys.queueKey,
+      constructQueueProps: activeKeys.constructProps
```
Comment (hayesry) [inline source/patterns/@aws-solutions-constructs/aws-sns-sqs/lib/index.ts:228]: nit: Is the `ConstructKeys` interface the best place to put `constructProps`? It seems that `constructProps` of type `sqs.QueueProps`, and written as `activeKeys.constructProps` stands out a little in an interface that mostly consists of encryption/key-related props. Not a blocker but stuck out to me a little.
