### PR TITLE
fix(wrapped constructs): shorten wrapped ID names in deprecated constructs

### LINKED ISSUE #369: Longer IDs in deprecated constructs breaking existing installations
[PR 315](https://github.com/awslabs/aws-solutions-constructs/pull/315) increased the length of the id by seven characters ("-wrapped") when it launches implementation of the construct with a new name inside the shel with the old name.

Unfortunately both the shell and the internal construct can't use the same name, so we must alter the id in some way if we don't alter the actual id sent from the client. We will:

* Change the added text to just "w" to reduce the number of implementations impacted
* The fix for impacted implementations is to switch the new constructs. As they are functionally equivalent, this is very simple - merely npm install'ing the new construct and changing the type references in the code.

There are about 8 renamed constructs where this pattern needs to be addressed.

### Reproduction Steps

See comment in [PR 315](https://github.com/awslabs/aws-solutions-constructs/pull/315)

### Environment

  - **CDK CLI Version      :**
  - **CDK Framework Version:**
  - **AWS Solutions Constructs Version     :**
  - **OS                   :**
  - **Language             :**

### Other

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by mickychetta**
*Issue #369 , if available:*

*Description of changes:*
-Replaced `-wrapped` with `W` in order to prevent the error of more than 64 characters in an ID name
-Updated all tests to support new id names

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

fixes #369

### CODE REVIEW

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: 773406c3185287733f45e876248c6ba5b59f4904
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f9b99f53-2881-4bcf-84a5-3eb116516013%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: 3eecc328867a0fd9fc3e45a07da7485f8c6f6601
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=739cfafd-8d02-4da2-8eb7-e816313ae79d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: 66ebb5dab5bbfb796fdaee5df4f984b76f79265b
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3154a8c8-b712-4776-bcb7-f2a22eee1ae5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: 9f007596ac84da2a7050194e8bc3930fde9d9900
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=26320645-e245-4d50-aa78-fc72e59af39b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

File: source/patterns/@aws-solutions-constructs/aws-dynamodb-stream-lambda/lib/index.ts [hunk 1]
```diff
@@ -83,7 +83,12 @@ export class DynamoDBStreamToLambda extends Construct {
   constructor(scope: Construct, id: string, props: DynamoDBStreamToLambdaProps) {
     super(scope, id);
     const convertedProps: DynamoDBStreamToLambdaProps = { ...props };
-    const wrappedConstruct: DynamoDBStreamToLambda = new DynamoDBStreamsToLambda(this, `${id}-wrapped`, convertedProps);
+
+    // W (for 'wrapped') is added to the id so that the id's of the constructs with the old and new names don't collide
+    // If this character pushes you beyond the 64 character limit, just import the new named construct and instantiate
+    // it in place of the older named version. They are functionally identical, aside from the types no other changes
+    // will be required.  (eg - new EventbridgeToLambda instead of DynamoDBStreamToLambda)
```
Comment (biffgaut) [inline source/patterns/@aws-solutions-constructs/aws-dynamodb-stream-lambda/lib/index.ts:90]: Cut/paste error here

File: source/patterns/@aws-solutions-constructs/aws-events-rule-sns/lib/index.ts [hunk 2]
```diff
@@ -86,6 +86,11 @@ export class EventsRuleToSns extends Construct {
   constructor(scope: Construct, id: string, props: EventsRuleToSnsProps) {
     super(scope, id);
     const convertedProps: EventsRuleToSnsProps = { ...props };
+
+    // W (for 'wrapped') is added to the id so that the id's of the constructs with the old and new names don't collide
+    // If this character pushes you beyond the 64 character limit, just import the new named construct and instantiate
+    // it in place of the older named version. They are functionally identical, aside from the types no other changes
+    // will be required.  (eg - new EventbridgeToSns instead of EventsRuleToSns)
     const wrappedConstruct: EventsRuleToSns = new EventbridgeToSns(this, `${id}`, convertedProps);
```
Comment (biffgaut) [inline source/patterns/@aws-solutions-constructs/aws-events-rule-sns/lib/index.ts:94]: uh...where's the W?

**Review by biffgaut — CHANGES_REQUESTED** [review]

**Comment by aws-solutions-constructs-team** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: a66f100b3c7d03eaa1638027280a454a1c3d3f4d
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8ad62d3c-4139-45bb-983f-4d41a9662237%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by biffgaut — APPROVED** [review]
